### ISSUE TITLE
Erro de Quantidade Máxima de Caracteres no campo Valor ao Criar uma Movimentação

### ISSUE THREAD

**Issue by Teodoro696** [doamaral/teste-nexus#11]
# Descrição
Ao Criar uma Movimentação do tipo **“Receitas”** no campo **“Valor”** ao informar uma quantidade superior a 13 numero no sistema está gerando um erro

# Passo-a-Passo
1. Logar no Sistema como usuário válido
2. Acessar o caminho: **Criar Movimentação**
5. Selecionar o "Tipo da Movimentação" a opção "Receita"
6. Informar uma "Data da Movimentação" válida superior a data atual
7. Informar uma "Data do Pagamento" 
8. Informar no campo "Descrição" uma descrição;
9. Informar no campo "Interessado" um Interessado
10. Informar no campo "Valor" um valor válio decimal com uma quantidade superior a 13 números;
11. Secionar a "Situação" a opção "Pago" 
12. Clicar no botão "Salva"

# Resultado Obtido
O sistema irá apresentar um erro "[object Object]"

# Resultado Esperado
Será necessário uma limitação do campo a uma quantidade de ate 13 numero de ate 13 

#Ambiente
Acesso no navegado Google Chrome (Versão 80.0.3987.122 (Versão oficial) 64 bits)

#Evidências
![Screenshot_2](https://user-images.githubusercontent.com/7263820/77228200-790cb900-6b64-11ea-89c8-2a924b0296e1.png)

**Comment by alexsandro-dev** [comment]
Valor não definido com total de caracteres

**Comment by alexsandro-dev** [comment]
Valor não definido
