### ISSUE TITLE
Erro ao Incluir Movimentação com Aba Navegador duplicada e sem a conta disponível, sistema está gerando um erro

### ISSUE THREAD

**Issue by Teodoro696** [doamaral/teste-nexus#4]
# Descrição

O cliente costuma operar 02 abas aberta no sistema, quando é gerada contas no sistema e em operação com outras abas em aberta, caso o cliente exclua um conta, e outro cliente estiver criando uma movimentação o sistema está gerado um erro.

# Passo-a-Passo
1. Logar no Sistema como usuário válido
2. Acessar o caminho: **Criar>Adicionar**
3. Informar uma Conta;
4. Duplicar aba do Navegado acessar o caminho: **Criar Movimentação**
5. No navegador na Aba Conta excluir a Conta Criada
6. Voltar para aba do Navegador **Criar Movimentação**
7. Selecionar o "Tipo da Movimentação" a opção "Receita"
8. Informar uma "Data da Movimentação" válida superior a data atual
9. Informar uma "Data do Pagamento" 
10. Informar no campo "Descrição";
11. Informar no campo "Interessado" um Interessado
12. Informar no campo "Valor" um valor válio decimal
13. Secionar a "Situação" a opção "Pago" 
14. Clicar no botão "Salva" 
 

# Resultado Obtido
O sistema irá apresentar um erro "[object Object]"

# Resultado Esperado
Será necessário validada uma Conta Criada  

#Ambiente
Acesso no navegado Google Chrome (Versão 80.0.3987.122 (Versão oficial) 64 bits)

#Evidências
![Screenshot_1](https://user-images.githubusercontent.com/7263820/77227713-12d26700-6b61-11ea-8f74-ddfbf00f9f0c.png)

**Comment by silviaamora** [comment]
Ok
