### ISSUE TITLE
Erro ao cadastrar uma quantidade máxima de caracteres no campo "Interessado" no menu "Criar Movimentação".

### ISSUE THREAD

**Issue by rafaelgiraoads** [doamaral/teste-nexus#5]
# Descrição
Ao cadastrar uma movimentação no menu "Criar movimento", caso o usuário preencha uma quantidade maior que 255 caracteres no campo "Interessado". O sistema está retornando um erro após salvar.

# Passo-a-Passo

1. Clicar no Menu "Criar Movimentação".
2. Selecionar o tipo de movimentação "Receita" ou "Despesa"
3. Digitar no campo "Data da Movimentação" uma data válida.
4. Digitar no campo "Data do Pagamento" uma data maior que a data da movimentação.
5. No campo "Descrição", preencher com nome (Colégio).
6. No campo "Interessado", preencher uma descrição maior que 255 caracteres.
7. No campo "Valor", preencher com o valor (700.00) 
8. No ComboBox "Conta", selecionar a conta (Rafael).
9. No Radio Button "Situação", selecionar a opção "pago" ou "pendente"
10. Clicar no botão salvar.

# Resultado Obtido

Após salvar, ocorre o seguinte erro: [object object].

# Resultado Esperado

O sistema deveria validar  quantidade máxima de caracteres suportado no campo "Interessado". 
O sistema deveria ter um contador regressivo de 255 - 0 no campo "Interessado", de forma que o usuário for digitando o interessado da movimentação, esse contador iria diminuindo. 

# Ambiente

Windows 10 PRO, versão 1903(Compilação 18362.720).
Google Chrome, Versão 80.0.3987.149 
Sistema, Seu Barriga (http://seubarriga.wcaquino.me)

# Evidências

Imagem em anexo.

**Comment by alexsandro-dev** [comment]
sem definição
